# This workflow checks for common grammar and spelling mistake in markdown docs files.
name: Spellcheck
on: workflow_dispatch

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ⚙️
        run: yarn install --frozen-lockfile

      - name: Spellcheck 📝
        uses: rojopolis/spellcheck-github-actions@0.33.0
        with:
          source_files: docs/**/*.md docs/**/*.mdx
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Output Spellcheck Results 📝
        uses: actions/upload-artifact@v3
        with:
          name: Spellcheck Output
          path: spellcheck-output.txt
